### ISSUE TITLE
root builder seems to be broken (again)

### ISSUE THREAD

**Issue by kkourt** [cilium/little-vm-helper-images#778]
See:
 * https://github.com/cilium/little-vm-helper-images/pull/776
 * https://github.com/cilium/little-vm-helper-images/pull/762
 * https://github.com/cilium/little-vm-helper-images/pull/747

**Comment by tklauser** [comment]
All builds seem to fail with:

```
#17 551.7 time="2024-12-03T18:50:33Z" level=warning msg="stderr> /etc/profile.d/70-systemd-shell-extra.sh: line 15: SHELL_PROMPT_PREFIX: unbound variable\n"
```

during bootstrap, e.g. https://github.com/cilium/little-vm-helper-images/actions/runs/12148379225/job/33876741983?pr=776#step:12:494

This is caused because the `networkd.sh` bootstrap script (and most other bootstrap scripts for that matter) source `/etc/profile` and thus transitively `/etc/profile.d/70-systemd-shell-extra.sh`. The bootstrap script has the nounset option set using `set -u`, and `/etc/profile.d/70-systemd-shell-extra.sh` checks for some `$SHELL_*` variables which might not be defined.

I think the proper fix is for the upstream systemd script to treat an unset variable as an empty string and I've submitted https://github.com/systemd/systemd/pull/35560 for that. In the short term we could just stop sourcing `/etc/profile` in the affected bootstrap scripts because I don't even know why this is needed.
